import Ember from 'ember';

export default Ember.ObjectController.extend({
   text: "",
   languages: [
       "Ada",
       "Algol",
       "Alice",
       "Assembly",
       "Basic",
       "C",
       "C#",
       "C++",
       "Clojure",
       "COBOL",
       "CoffeeScript",
       "Dart",
       "Delphi",
       "ECMAScript",
       "Erlang",
       "F#",
       "Fortran",
       "FoxPro",
       "Go",
       "Groovy",
       "Haskell",
       "J#",
       "Java",
       "JavaScript",
       "JScript",
       "Lisp",
       "Logo",
       "Magic",
       "MATLAB",
       "Mercury",
       "Monkey",
       "Modula-2",
       "Objective-C",
       "OCaml",
       "Pascal",
       "Perl",
       "PHP",
       "PL/SQL",
       "Prolog",
       "Python",
       "Q",
       "R",
       "Ruby",
       "Rust",
       "Scala",
       "Scheme",
       "Smalltalk",
       "Tcl",
       "Turing",
       "TypeScript",
       "VBScript",
       "Visual Basic",
       "Whitespace",
       "xBase"
   ]
});
